apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-docker
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: hello-world
    spec:     # pod spec
      containers:
        - name: test-docker
          image: test-docker # image we pushed
          ports:
            - containerPort: 8000