apiVersion: v1
kind: Pod
metadata:
  name: test-docker
  labels:
    app: web
spec:
  containers:
    - name: test-docker
      image: test-docker
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
          hostPort: 8080